backend_ws_client_save:
    path:     /client
    defaults: { _controller: BackendWebServiceBundle:Client:save }
    methods:  [ POST ]
    options:
        expose: true

backend_ws_client_show:
    path:     /client/{id}
    defaults: { _controller: BackendWebServiceBundle:Client:show }
    methods:  [ GET ]
    requirements:
        id: \d+
    options:
        expose: true

backend_ws_client_update:
    path:     /client/{id}
    defaults: { _controller: BackendWebServiceBundle:Client:update }
    methods:  [ PUT ]
    requirements:
        id: \d+
    options:
        expose: true
