backend_ws_comment_create:
    path:     /comment/create
    defaults: { _controller: BackendWebServiceBundle:Comments:create }
    options:
        expose: true

backend_ws_comment_delete:
    path:     /comments/{id}/delete
    defaults: { _controller: BackendWebServiceBundle:Comments:delete }
    options:
        expose: true

backend_ws_comment_patch:
    path:     /comments/{id}
    defaults: { _controller: BackendWebServiceBundle:Comments:patch }
    methods:  [ PATCH ]
    options:
        expose: true

backend_ws_comment_update:
    path:     /comments/{id}/update
    defaults: { _controller: BackendWebServiceBundle:Comments:update }
    options:
        expose: true

backend_ws_comments_batch_delete:
    path:     /comments/batch-delete
    defaults: { _controller: BackendWebServiceBundle:Comments:batchDelete }
    options:
        expose: true

backend_ws_comments_patch:
    path:     /comments
    defaults: { _controller: BackendWebServiceBundle:Comments:patchSelected }
    methods:  [ PATCH ]
    options:
        expose: true

backend_ws_comments_list:
    path:     /comments{format}
    defaults: { _controller: BackendWebServiceBundle:Comments:list, format: '.json' }
    methods:  [ GET ]
    requirements:
        format: '.json|.csv'
    options:
        expose: true
