backend_ws_domain_check_available:
    path:     /domains/available
    defaults: { _controller: BackendWebServiceBundle:DomainManagement:checkAvailable }
    methods:  [ GET ]
    options:
        expose: true

backend_ws_domain_check_configured:
    path:     /domains/configured
    defaults: { _controller: BackendWebServiceBundle:DomainManagement:checkConfigured }
    methods:  [ GET ]
    options:
        expose: true

backend_ws_domain_check_valid:
    path:     /domains/valid
    defaults: { _controller: BackendWebServiceBundle:DomainManagement:checkValid }
    methods:  [ GET ]
    options:
        expose: true

backend_ws_domain_delete:
    path:     /domains/{id}
    defaults: { _controller: BackendWebServiceBundle:DomainManagement:delete }
    methods:  [ DELETE ]
    options:
        expose: true

backend_ws_domain_save:
    path:    /domains
    defaults: { _controller: BackendWebServiceBundle:DomainManagement:save}
    methods: [ POST ]
    options:
        expose: true

backend_ws_domains_list:
    path: /domains
    defaults: { _controller: BackendWebServiceBundle:DomainManagement:list}
    options:
        expose: true
