backend_ws_purchase_get_pdf:
    path: /purchases/{id}.pdf
    defaults: { _controller: BackendWebServiceBundle:Purchase:getPdf }
    methods:  [ GET ]
    options:
        expose: true

backend_ws_purchases_list:
    path: /purchases
    defaults: { _controller: BackendWebServiceBundle:Purchase:list }
    methods: [ GET ]
    options:
        expose: true

backend_ws_purchase_save:
    path: /purchases
    defaults: { _controller: BackendWebServiceBundle:Purchase:save }
    methods: [ POST ]
    options:
        expose: true

backend_ws_purchase_show:
    path: /purchases/{id}
    defaults: { _controller: BackendWebServiceBundle:Purchase:show }
    methods: [ GET ]
    options:
        expose: true

backend_ws_purchase_update:
    path: /purchases/{id}
    defaults: { _controller: BackendWebServiceBundle:Purchase:update }
    methods: [ PUT ]
    options:
        expose: true
