backend_ws_user_create:
    path:     /user/create
    defaults: { _controller  : BackendWebServiceBundle:Users:create }
    options:
        expose: true

backend_ws_user_delete:
    path:     /users/{id}/delete
    defaults: { _controller  : BackendWebServiceBundle:Users:delete }
    options:
        expose: true

backend_ws_user_show:
    path:     /users/{id}/show
    defaults: { _controller  : BackendWebServiceBundle:Users:show }
    options:
        expose: true

backend_ws_user_update:
    path:     /users/{id}/update
    defaults: { _controller  : BackendWebServiceBundle:Users:update }
    options:
        expose: true

backend_ws_users_batch_delete:
    path:     /users/batch-delete
    defaults: { _controller  : BackendWebServiceBundle:Users:batchDelete }
    options:
        expose: true

backend_ws_users_list:
    path:     /users
    defaults: { _controller  : BackendWebServiceBundle:Users:list }
    options:
        expose: true
