frontend_author_frontpage:
    path: /author/{slug}
    defaults: { _controller: FrontendBundle:Author:authorFrontpage }
    requirements:
        slug: '[^/]+'
    options:
        l10n: true

frontend_frontpage_authors:
    path: /authors
    defaults: { _controller: FrontendBundle:Author:frontpageAuthors }
    options:
        l10n: true

frontend_external_author_frontpage:
    path: /extauthor/{slug}
    defaults: { _controller: FrontendBundle:Author:extAuthorFrontpage }
    requirements:
        slug: '[^/]+'
