category_frontpage:
    path: /blog/section/{category_name}
    defaults: { _controller: FrontendBundle:Category:category }
    requirements:
        category: '[^/]+'

categ_sync_frontpage:
    path: /extseccion/blog/{category_name}
    defaults: { _controller: FrontendBundle:Category:extCategory }
    requirements:
        category: '[^/]+'
