category_homepage:
    path:     /{category_slug}/
    defaults: { _controller: FrontendBundle:Category:homepage }
    requirements:
        category_slug: '[^/]+'
    options:
        l10n: true
        subdirectory: true

category_frontpage:
    path:     /blog/section/{category_slug}/
    defaults: { _controller: FrontendBundle:Category:list }
    requirements:
        category_slug: '[^/]+'
    options:
        l10n: true
        subdirectory: true

categ_sync_frontpage:
    path:     /extseccion/blog/{category_slug}/
    defaults: { _controller: FrontendBundle:Category:extCategory }
    requirements:
        category_slug: '[^/]+'
    options:
        subdirectory: true
