parameters:
    environment:       development # production
    database:
        dbal:
            default_connection: default
            connections:
                default:
                    driver:               mysqli
                    dbname:               onm-instances
                    host:                 localhost
                    port:                 3306
                    user:                 root
                    password:             root
                    charset:              UTF-8
                    # slaves:
                    #     slave1:
                    #         driver:               mysqli
                    #         dbname:               ~
                    #         host:                 localhost
                    #         port:                 ~
                    #         user:                 root
                    #         password:             root
                    #         charset:              ~

    mailer_transport:  mail
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~
    mailer_protocol:   ~
    mailer_port:       ~
    mailer_no_reply_address: no-reply@postman.opennemas.com

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt

    cache_handler:     Onm\Cache\Apc
    cache_handler_params:
        server: 127.0.0.1
        port: 11211
        connection_string: tcp:\\127.0.0.1
        options:
            server: localhost
            prefix: onm

    dispatcher.exceptionhandler: "Framework:Controllers:ErrorController:default"
    session_params:
        save_path:     tmp/instances
        name: _onm_sess

    logger_file_path: tmp/log/application.log
    dev_token: 1234

    manager_webservice:
        api_key:         sheequaiJie5deewijie6oojaiShie5R
        company_mail:    support@openenmas.com
        info_mail:       info@openhost.es
        no_reply_sender: no-reply@postman.opennemas.com
        no_reply_from:   no-reply@opennemas.com

    instance_creator:
        end_point:   https://manager.onm.local/managerws/
        base_domain: opennemas.com
        template:    retrincos
