backend:
    resource: @BackendBundle/Resources/config/routing.yml
    prefix:   /admin

frontendmobile:
    resource: @FrontendMobileBundle/Resources/config/routing.yml
    prefix:   /mobile

manager_webservice:
    resource: @ManagerWebServiceBundle/Resources/config/routing.yml
    prefix:   /managerws

manager:
    resource: @ManagerBundle/Resources/config/routing.yml
    prefix:   /manager

webservice:
    resource: @WebServiceBundle/Resources/config/routing.yml
    prefix:   /ws

frontend:
    resource: @FrontendBundle/Resources/config/routing.yml
    prefix:   /

backend_webservice:
    resource: @BackendWebServiceBundle/Resources/config/routing.yml
    prefix:   /admin/entityws

# base paths
admin_welcome:
    path: '/admin'
    defaults: { _controller  : BackendBundle:Welcome:default }

manager_welcome:
    path: '/manager'
    defaults: { _controller: ManagerBundle:Welcome:default }

frontendmobile_root:
    path: '/mobile'
    defaults: { _controller : FrontendMobileBundle:Frontpages:show }
