backend_attachment_create:
    path:     /attachments/new/
    defaults: { _controller: BackendBundle:Attachment:create }

backend_attachment_show:
    path:     /attachments/{id}/
    defaults: { _controller: BackendBundle:Attachment:show }
    requirements:
        id: \d+
    options:
        expose: true

backend_attachments_list:
    path:     /attachments/
    defaults: { _controller: BackendBundle:Attachment:list }
    options:
        expose: true
