backend_cache_config:
    path:     /system/cache/{service}/
    defaults: { _controller: BackendBundle:Cache:config }
    options:
        expose: true
    requirements:
        service: 'smarty'

backend_cache_list:
    path:     /system/cache/
    defaults: { _controller: BackendBundle:Cache:list }
    options:
        expose: true
