backend_category_create:
    path:     /categories/new/
    defaults: { _controller: BackendBundle:Category:create }
    options:
        expose: true

backend_category_show:
    path:     /categories/{id}/
    defaults: { _controller: BackendBundle:Category:show }
    options:
        expose: true
    requirements:
        id: \d+

backend_categories_list:
    path:     /categories/
    defaults: { _controller: BackendBundle:Category:list }
    options:
        expose: true
