backend_poll_create:
    path:     /polls/new/
    defaults: { _controller: BackendBundle:Poll:create }

backend_poll_show:
    path:     /polls/{id}/
    defaults: { _controller: BackendBundle:Poll:show }
    requirements:
        id: \d+
    options:
        expose: true

backend_polls_content_provider:
    path:     /polls/content-provider/
    defaults: { _controller: BackendBundle:Poll:contentProvider }

backend_polls_list:
    path:     /polls/
    defaults: { _controller: BackendBundle:Poll:list }
    options:
        expose: true
