manager_ws_purchase_create:
    path:     /purchases
    defaults: { _controller: ManagerWebServiceBundle:Purchase:create }
    methods:  [ POST ]
    options:
        expose: true

manager_ws_purchase_delete:
    path:     /purchases/{id}
    defaults: { _controller: ManagerWebServiceBundle:Purchase:delete }
    methods:  [ DELETE ]
    requirements:
        id: \d+
    options:
        expose: true

manager_ws_purchase_get_pdf:
    path:     /purchases/{id}.pdf
    defaults: { _controller: ManagerWebServiceBundle:Purchase:getPdf }
    methods:  [ GET ]
    requirements:
        id: \d+
    options:
        expose: true

manager_ws_purchase_new:
    path:     /purchases/new
    defaults: { _controller: ManagerWebServiceBundle:Purchase:new }
    methods:  [ GET ]
    options:
        expose: true

manager_ws_purchase_patch:
    path:     /purchases/{id}
    defaults: { _controller: ManagerWebServiceBundle:Purchase:patch }
    methods:  [ PATCH ]
    options:
        expose: true

manager_ws_purchase_show:
    path:     /purchases/{id}
    defaults: { _controller: ManagerWebServiceBundle:Purchase:show }
    methods:  [ GET ]
    requirements:
        id: \d+
    options:
        expose: true

manager_ws_purchase_update:
    path:     /purchases/{id}
    defaults: { _controller: ManagerWebServiceBundle:Purchase:update }
    methods:  [ PUT ]
    requirements:
        id: \d+
    options:
        expose: true

manager_ws_purchases_delete:
    path:     /purchases
    defaults: { _controller: ManagerWebServiceBundle:Purchase:deleteSelected }
    methods:  [ DELETE ]
    options:
        expose: true

manager_ws_purchases_export_all:
    path:     /purchases/all.csv
    defaults: { _controller: ManagerWebServiceBundle:Purchase:exportAll}
    methods:  [ GET ]
    options:
        expose: true

manager_ws_purchases_export_completed:
    path:     /purchases/completed.csv
    defaults: { _controller: ManagerWebServiceBundle:Purchase:exportCompleted }
    methods:  [ GET ]
    options:
        expose: true

manager_ws_purchases_export_uncompleted:
    path:     /purchases/uncompleted.csv
    defaults: { _controller: ManagerWebServiceBundle:Purchase:exportUncompleted }
    methods:  [ GET ]
    options:
        expose: true

manager_ws_purchases_list:
    path:     /purchases
    defaults: { _controller: ManagerWebServiceBundle:Purchase:list }
    methods:  [ GET ]
    options:
        expose: true

manager_ws_purchases_patch:
    path:     /purchases
    defaults: { _controller: ManagerWebServiceBundle:Purchase:patchSelected }
    methods:  [ PATCH ]
    options:
        expose: true
