manager_ws_user_autocomplete:
    path:     /users/autocomplete
    defaults: { _controller: ManagerWebServiceBundle:User:autocomplete }
    methods:  [ GET ]
    options:
        expose: true
manager_ws_user_delete:
    path:     /users/{id}
    defaults: { _controller: ManagerWebServiceBundle:User:delete }
    methods:  [ DELETE ]
    options:
        expose: true

manager_ws_user_new:
    path:     /users/new
    defaults: { _controller: ManagerWebServiceBundle:User:new }
    methods:  [ GET ]
    options:
        expose: true

manager_ws_user_patch:
    path:     /users/{id}
    defaults: { _controller: ManagerWebServiceBundle:User:patch }
    methods:  [ PATCH ]
    options:
        expose: true

manager_ws_user_save:
    path:     /users
    defaults: { _controller: ManagerWebServiceBundle:User:save }
    methods:  [ POST ]
    options:
        expose: true

manager_ws_user_show:
    path:     /users/{id}
    defaults: { _controller: ManagerWebServiceBundle:User:show }
    methods:  [ GET ]
    options:
        expose: true

manager_ws_user_show_me:
    path:     /users/me
    defaults: { _controller: ManagerWebServiceBundle:User:showMe }
    methods:  [ GET ]
    options:
        expose: true

manager_ws_user_update:
    path:     /users/{id}
    defaults: { _controller: ManagerWebServiceBundle:User:update }
    methods:  [ PUT ]
    options:
        expose: true

manager_ws_users_delete:
    path:     /users
    defaults: { _controller: ManagerWebServiceBundle:User:deleteSelected }
    methods:  [ DELETE ]
    options:
        expose: true

manager_ws_users_list:
    path:     /users
    defaults: { _controller: ManagerWebServiceBundle:User:list, format: 'json'  }
    methods:  [ GET ]
    options:
        expose: true

manager_ws_users_patch:
    path:     /users
    defaults: { _controller: ManagerWebServiceBundle:User:patchSelected }
    methods:  [ PATCH ]
    options:
        expose: true
