manager_ws_user_delete:
    path:     /user/{id}/delete
    defaults: { _controller: ManagerWebServiceBundle:User:delete }
    options:
        expose: true

manager_ws_user_set_activated:
    path:     /user/{id}/set-activated
    defaults: { _controller: ManagerWebServiceBundle:User:setActivated }
    options:
        expose: true

manager_ws_user_show:
    path:     /user/{id}/show
    defaults: { _controller: ManagerWebServiceBundle:User:show }
    options:
        expose: true

manager_ws_users_delete:
    path:     /users/delete
    defaults: { _controller: ManagerWebServiceBundle:User:batchDelete }
    options:
        expose: true

manager_ws_users_list:
    path:     /users/list
    defaults: { _controller: ManagerWebServiceBundle:User:list }
    options:
        expose: true

manager_ws_users_list_export:
    path: /user/list-export.csv
    defaults: { _controller:  ManagerWebServiceBundle:User:export }

manager_ws_users_set_activated:
    path:     /users/set-activated
    defaults: { _controller: ManagerWebServiceBundle:User:batchSetActivated }
    options:
        expose: true
