parameters:
    core.helper.comment.default_params:
        disable_comments: false
        with_comments: true
        number_elements: 10
        moderation_manual: true
        moderation_autoreject: false
        moderation_autoaccept: false
        required_email: false
services:
    core.helper.advertisement:
        class:     Common\Core\Component\Helper\AdvertisementHelper
        arguments: [ '@service_container' ]
        public:    true

    core.helper.attachment:
        class:     Common\Core\Component\Helper\AttachmentHelper
        arguments: [ '@core.loader.instance', '%core.paths.public%' ]
        public:    true

    core.helper.comment:
        class:     Common\Core\Component\Helper\CommentHelper
        arguments: [ '@orm.manager', '%core.helper.comment.default_params%' ]
        public:    true

    core.helper.content:
        class:      Common\Core\Component\Helper\ContentHelper
        arguments:  [ '@entity_repository', '@api.service.content', '@cache.connection.instance' ]
        public:     true

    core.helper.checkout:
        class:     Common\Core\Component\Helper\CheckoutHelper
        arguments: [ '@service_container' ]
        public:    true

    core.helper.content_media:
        class:     Common\Core\Component\Helper\ContentMediaHelper
        arguments: [ '@service_container', '@orm.manager', '@entity_repository' ]
        public:    true

    core.helper.csv:
        class:     Common\Core\Component\Helper\CsvHelper
        public:    true

    core.helper.http_fetcher:
        class:     Common\Core\Component\Http\Fetcher
        public:    true

    core.helper.hwi_oauth:
        class:     Common\Core\Component\Helper\HwiOauthHelper
        arguments: [ '@router' , '@hwi_oauth.templating.helper.oauth' ]
        public:    true

    core.helper.image:
        class:     Common\Core\Component\Helper\ImageHelper
        arguments: [ '@core.loader.instance', '%core.paths.public%', '@core.image.processor' ]
        public:    true

    core.helper.instance:
        class:     Common\Core\Component\Helper\InstanceHelper
        arguments: [ '@orm.connection.instance', '%core.paths.media%' ]
        public:    true

    core.helper.instance_sync:
        class:     Common\Core\Component\Helper\InstanceSyncHelper
        arguments: [ '@service_container' ]
        public:    true

    core.helper.locale:
        class:     Common\Core\Component\Helper\LocaleHelper
        arguments: [ '@orm.manager', '@core.instance', '@core.locale', '@request_stack', '@core.security' ]
        public:    true

    core.helper.l10n_route:
        class:     Common\Core\Component\Helper\L10nRouteHelper
        arguments: [ '@service_container' ]
        public:    true

    core.helper.newsletter:
        class:     Common\Core\Component\Helper\NewsletterHelper
        arguments: [ '@orm.manager', '@api.service.subscription' ]
        public:    true

    core.helper.newsletter_sender:
        class:     Common\Core\Component\Helper\NewsletterSenderHelper
        arguments:
            - '@orm.manager'
            - '@error.log'
            - '@application.log'
            - '@core.instance'
            - '@mailer'
            - '@api.service.subscription'
            - '@external.act_on.factory'
            - '@api.service.newsletter'
            - '%mailer_no_reply_address%'
        public: true

    core.helper.newsstand:
        class:     Common\Core\Component\Helper\NewsstandHelper
        arguments: [ '@core.loader.instance', '%core.paths.public%' ]
        public:    true

    core.helper.oql:
        class:     Common\Core\Component\Helper\OqlHelper
        arguments: [ '@service_container' ]
        public:    true

    core.helper.permission:
        class:     Common\Core\Component\Helper\PermissionHelper
        arguments: [ '@core.security' ]
        public:    true

    core.helper.structured_data:
        class:     Common\Core\Component\Helper\StructuredData
        arguments: [ '@service_container' ]
        public:    true

    core.helper.subscription:
        class:     Common\Core\Component\Helper\SubscriptionHelper
        arguments: [ '@core.helper.permission', '@core.security', '@api.service.subscription' ]
        public:    true

    core.helper.url:
        class:     Common\Core\Component\Helper\UrlHelper
        public:    true

    core.helper.url_generator:
        class:     Common\Core\Component\Helper\UrlGeneratorHelper
        arguments: [ '@service_container' ]
        public:    true

    core.helper.user:
        class:     Common\Core\Component\Helper\UserHelper
        arguments: [ '@service_container' ]
        public:    true
