parameters:
   onm_test.example.class: Onm\TestBundle\Example

services:
    manager_ws_login_success_handler:
        class:     ManagerWebService\EventListener\LoginSuccessHandler
        arguments: [ '@security.token_storage', '@router', '@session' ]
