backend_ws_advertisements:
    resource: '@BackendWebServiceBundle/Resources/config/routing/advertisements.yml'
    prefix:   /

backend_ws_article:
    resource: '@BackendWebServiceBundle/Resources/config/routing/article.yml'
    prefix:   /

backend_ws_client:
    resource: '@BackendWebServiceBundle/Resources/config/routing/client.yml'
    prefix:   /

backend_ws_category:
    resource: '@BackendWebServiceBundle/Resources/config/routing/category.yml'
    prefix:   /

backend_ws_comments:
    resource: '@BackendWebServiceBundle/Resources/config/routing/comments.yml'
    prefix:   /

backend_ws_domain:
    resource: '@BackendWebServiceBundle/Resources/config/routing/domain.yml'
    prefix:   /

backend_ws_getting_started:
    resource: '@BackendWebServiceBundle/Resources/config/routing/getting_started.yml'
    prefix:   /
backend_ws_letters:
    resource: '@BackendWebServiceBundle/Resources/config/routing/letter.yml'
    prefix:   /

backend_ws_menus:
    resource: '@BackendWebServiceBundle/Resources/config/routing/menus.yml'
    prefix:   /

backend_ws_news_agency_server:
    resource: '@BackendWebServiceBundle/Resources/config/routing/news_agency_server.yml'
    prefix:   /

backend_ws_news_agency:
    resource: '@BackendWebServiceBundle/Resources/config/routing/news_agency.yml'
    prefix:   /

backend_ws_opinions:
    resource: '@BackendWebServiceBundle/Resources/config/routing/opinions.yml'
    prefix:   /

backend_ws_picker:
    resource: '@BackendWebServiceBundle/Resources/config/routing/picker.yml'
    prefix:   /

backend_ws_purchase:
    resource: '@BackendWebServiceBundle/Resources/config/routing/purchase.yml'
    prefix:   /

backend_ws_store:
    resource: '@BackendWebServiceBundle/Resources/config/routing/store.yml'
    prefix:   /

backend_ws_theme:
    resource: '@BackendWebServiceBundle/Resources/config/routing/theme.yml'
    prefix:   /

backend_ws_users:
    resource: '@BackendWebServiceBundle/Resources/config/routing/users.yml'
    prefix:   /

backend_ws_usergroups:
    resource: '@BackendWebServiceBundle/Resources/config/routing/usergroups.yml'
    prefix:   /

backend_ws_widgets:
    resource: '@BackendWebServiceBundle/Resources/config/routing/widgets.yml'
    prefix:   /

backend_ws_keywords:
    resource: '@BackendWebServiceBundle/Resources/config/routing/keywords.yml'
    prefix:   /

backend_ws_notification:
    resource: '@BackendWebServiceBundle/Resources/config/routing/notification.yml'
    prefix:   /

backend_ws_image:
    resource: '@BackendWebServiceBundle/Resources/config/routing/image.yml'
    prefix:   /

backend_ws_content_v2:
    resource: '@BackendWebServiceBundle/Resources/config/routing/content_v2.yml'
    prefix:   /

backend_ws_content:
    resource: '@BackendWebServiceBundle/Resources/config/routing/content.yml'
    prefix:   /
