orm:
    metadata:
        -
            name: Invoice
            required:
                - client_id
                - date
                - lines
                - status
            properties:
                client_id: integer
                date:      datetime
                id:        integer
                lines:     array
                notes:     string
                status:    string
                terms:     string
            converters:
                default:
                    class:     Common\ORM\Database\Data\Converter\BaseConverter
                    arguments: [ '%freshbooks.domain%', '%freshbooks.token%', '@orm.metadata.invoice' ]
            repositories:
                freshbooks:
                    class:     Common\ORM\FreshBooks\Repository\InvoiceRepository
                    arguments: [ '%freshbooks.domain%', '%freshbooks.token%', '@orm.metadata.invoice' ]
            persisters:
                freshbooks:
                    class:     Common\ORM\FreshBooks\Persister\InvoicePersister
                    arguments: [ '%freshbooks.domain%', '%freshbooks.token%', '@orm.metadata.invoice' ]
            mapping:
                freshbooks:
                    client_id:
                        name: client_id
                        type: string
                    date:
                        name: date
                        type: string
                    lines:
                        name: lines
                        type: array
                    notes:
                        name: notes
                        type: string
                    status:
                        name: status
                        type: string
                    terms:
                        name: terms
                        type: string
