frontend_robots:
    path: /robots.txt
    defaults: { _controller: FrontendBundle:Robots:index }

utilities_sharrre:
    path: /utilities/sharrre
    defaults: { _controller: FrontendBundle:Utilities:sharrre }

frontend_playground:
    path: /playground/{action}
    defaults: { _controller: FrontendBundle:Playground:default }

frontend_advertisement:
    resource: '@FrontendBundle/Resources/config/routing/advertisement.yml'

frontend_album:
    resource: '@FrontendBundle/Resources/config/routing/album.yml'

frontend_archive:
    resource: '@FrontendBundle/Resources/config/routing/archive.yml'

frontend_article:
    resource: '@FrontendBundle/Resources/config/routing/article.yml'

frontend_asset:
    resource: '@FrontendBundle/Resources/config/routing/asset.yml'

frontend_authentication:
    resource: '@FrontendBundle/Resources/config/routing/authentication.yml'

frontend_author:
    resource: '@FrontendBundle/Resources/config/routing/author.yml'

frontend_blog:
    resource: '@FrontendBundle/Resources/config/routing/blog.yml'

frontend_book:
    resource: '@FrontendBundle/Resources/config/routing/book.yml'

frontend_category:
    resource: '@FrontendBundle/Resources/config/routing/category.yml'

frontend_comment:
    resource: '@FrontendBundle/Resources/config/routing/comment.yml'

frontend_content:
    resource: '@FrontendBundle/Resources/config/routing/content.yml'

frontend_event:
    resource: '@FrontendBundle/Resources/config/routing/event.yml'

frontend_form:
    resource: '@FrontendBundle/Resources/config/routing/form.yml'

frontend_framework:
    resource: '@FrontendBundle/Resources/config/routing/framework.yml'

frontend_frontpage:
    resource: '@FrontendBundle/Resources/config/routing/frontpage.yml'

frontend_letter:
    resource: '@FrontendBundle/Resources/config/routing/letter.yml'

frontend_monograph:
    resource: '@FrontendBundle/Resources/config/routing/monograph.yml'

frontend_newsletter:
    resource: '@FrontendBundle/Resources/config/routing/newsletter.yml'

frontend_newstand:
    resource: '@FrontendBundle/Resources/config/routing/newstand.yml'

frontend_opinion:
    resource: '@FrontendBundle/Resources/config/routing/opinion.yml'

frontend_password:
    resource: '@FrontendBundle/Resources/config/routing/password.yml'

frontend_paywall:
    resource: '@FrontendBundle/Resources/config/routing/paywall.yml'

frontend_poll:
    resource: '@FrontendBundle/Resources/config/routing/poll.yml'

frontend_redirect:
    resource: '@FrontendBundle/Resources/config/routing/redirect.yml'

frontend_rss:
    resource: '@FrontendBundle/Resources/config/routing/rss.yml'

frontend_search:
    resource: '@FrontendBundle/Resources/config/routing/search.yml'

frontend_sitemap:
    resource: '@FrontendBundle/Resources/config/routing/sitemap.yml'

frontend_static_page:
    resource: '@FrontendBundle/Resources/config/routing/static_page.yml'

frontend_tag:
    resource: '@FrontendBundle/Resources/config/routing/tag.yml'

frontend_user:
    resource: '@FrontendBundle/Resources/config/routing/user.yml'

frontend_video:
    resource: '@FrontendBundle/Resources/config/routing/video.yml'

frontend_widget:
    resource: '@FrontendBundle/Resources/config/routing/widget.yml'
