orm:
    schema:
        -
            name: instance
            entities:
                - Category
                - Content
                - User
                - UserGroup
                - UserGroupPrivileges
                - Url
