api_v1_backend_event_create_item:
    path:     /events/new
    defaults: { _controller: ApiBundle:V1/Backend/Event:createItem }
    methods:  [ GET ]
    options:
        expose: true

api_v1_backend_event_delete_item:
    path:     /events/{id}
    defaults: { _controller: ApiBundle:V1/Backend/Event:deleteItem }
    methods:  [ DELETE ]
    options:
        expose: true
    requirements:
        id: \d+

api_v1_backend_event_delete_list:
    path:     /events
    defaults: { _controller: ApiBundle:V1/Backend/Event:deleteList }
    methods:  [ DELETE ]
    options:
        expose: true

api_v1_backend_event_get_item:
    path:     /events/{id}
    defaults: { _controller: ApiBundle:V1/Backend/Event:getItem }
    methods:  [ GET ]
    options:
        expose: true
    requirements:
        id: \d+

api_v1_backend_event_get_list:
    path:     /events
    defaults: { _controller: ApiBundle:V1/Backend/Event:getList, format: '.json' }
    methods:  [ GET ]
    options:
        expose: true

api_v1_backend_event_patch_item:
    path:     /events/{id}
    defaults: { _controller: ApiBundle:V1/Backend/Event:patchItem }
    methods:  [ PATCH ]
    options:
        expose: true
    requirements:
        id: \d+

api_v1_backend_event_patch_list:
    path:     /events
    defaults: { _controller: ApiBundle:V1/Backend/Event:patchList }
    methods:  [ PATCH ]
    options:
        expose: true

api_v1_backend_event_save_item:
    path:     /events
    defaults: { _controller: ApiBundle:V1/Backend/Event:saveItem }
    methods:  [ POST ]
    options:
        expose: true

api_v1_backend_event_update_item:
    path:     /events/{id}
    defaults: { _controller: ApiBundle:V1/Backend/Event:updateItem }
    methods:  [ PUT ]
    options:
        expose: true
    requirements:
        id: \d+

api_v1_backend_event_get_config:
    path:     /events/config
    defaults: { _controller: ApiBundle:V1/Backend/Event:getConfig }
    methods:  [ GET ]
    options:
        expose: true

api_v1_backend_event_save_config:
    path:     /events/config
    defaults: { _controller: ApiBundle:V1/Backend/Event:saveConfig }
    methods:  [ PUT ]
    options:
        expose: true
