api_v1_backend_subscription_create_item:
    path:     /subscriptions/new
    defaults: { _controller: ApiBundle:V1/Backend/Subscription:createItem }
    methods:  [ GET ]
    options:
        expose: true

api_v1_backend_subscription_delete_item:
    path:     /subscriptions/{id}
    defaults: { _controller: ApiBundle:V1/Backend/Subscription:deleteItem }
    methods:  [ DELETE ]
    options:
        expose: true

api_v1_backend_subscription_delete_list:
    path:     /subscriptions
    defaults: { _controller: ApiBundle:V1/Backend/Subscription:deleteList }
    methods:  [ DELETE ]
    options:
        expose: true

api_v1_backend_subscription_get_item:
    path:     /subscriptions/{id}
    defaults: { _controller: ApiBundle:V1/Backend/Subscription:getItem }
    methods:  [ GET ]
    options:
        expose: true

api_v1_backend_subscription_get_list:
    path:     /subscriptions
    defaults: { _controller: ApiBundle:V1/Backend/Subscription:getList, format: '.json' }
    methods:  [ GET ]
    options:
        expose: true

api_v1_backend_subscription_patch_item:
    path:     /subscriptions/{id}
    defaults: { _controller: ApiBundle:V1/Backend/Subscription:patchItem }
    methods:  [ PATCH ]
    options:
        expose: true

api_v1_backend_subscription_patch_list:
    path:     /subscriptions
    defaults: { _controller: ApiBundle:V1/Backend/Subscription:patchList }
    methods:  [ PATCH ]
    options:
        expose: true

api_v1_backend_subscription_save_item:
    path:     /subscriptions
    defaults: { _controller: ApiBundle:V1/Backend/Subscription:saveItem }
    methods:  [ POST ]
    options:
        expose: true

api_v1_backend_subscription_update_item:
    path:     /subscriptions/{id}
    defaults: { _controller: ApiBundle:V1/Backend/Subscription:updateItem }
    methods:  [ PUT ]
    options:
        expose: true
